In [6]:
import pandas as pd
import numpy as np

In [7]:
mainpath = r'/Users/lgutierrez/Documents/Desarrollo/iron-hack/module-1/12-pandas-numpy/datasets/'
filename = r'vehicles.csv'
fullpath = mainpath+filename
data = pd.read_csv(fullpath)
data.head()


Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5   
1        AM General     FJ8c Post Office  1984                  4.2   
2        AM General  Post Office DJ5 2WD  1985                  2.5   
3        AM General  Post Office DJ8 2WD  1985                  4.2   
4  ASC Incorporated                  GNX  1987                  3.8   

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD   
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD   
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars   

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17   
1   Regular          25.354615        13           13            13   
2   Regular          20.600625        16           17            16   
3   Regular          25.354615        13           13            13   
4   Premium          20.600625        14           21            16   

   CO2 Emission Grams/Mile  Fuel Cost/Year  
0               522.764706            1950  
1               683.615385            2550  
2               555.437500            2100  
3               683.615385            2550  
4               555.437500            2550

In [9]:
print(pd.__version__)
print(np.__version__)

1.2.3
1.20.1


In [10]:
serie = pd.Series(np.random.randint(100,size=10))
print(serie)

0    38
1    39
2     3
3    81
4    62
5    55
6     2
7     7
8    12
9    50
dtype: int32


In [12]:
serie[3]

81

In [14]:
df = pd.DataFrame(np.random.randint(100, size=[10,4]))
df

0   1   2   3
0  32   3  66  75
1  65  56  71  44
2  44  25  18  81
3  37  51  69  34
4  92  44  94  85
5  47  56  90  96
6  19  25  58   7
7  89  17  63  34
8  35  58   3  55
9  35  24  71  81

In [15]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [16]:
df[0]

0    32
1    65
2    44
3    37
4    92
5    47
6    19
7    89
8    35
9    35
Name: 0, dtype: int32

In [18]:
df = df.rename(columns = {0:"columna_1", 1:"columna_2", 2:"columna_3", 3:"columna_4"})
df

columna_1  columna_2  columna_3  columna_4
0         32          3         66         75
1         65         56         71         44
2         44         25         18         81
3         37         51         69         34
4         92         44         94         85
5         47         56         90         96
6         19         25         58          7
7         89         17         63         34
8         35         58          3         55
9         35         24         71         81

In [19]:
df.columns = ["A","B","C","D"]
df

A   B   C   D
0  32   3  66  75
1  65  56  71  44
2  44  25  18  81
3  37  51  69  34
4  92  44  94  85
5  47  56  90  96
6  19  25  58   7
7  89  17  63  34
8  35  58   3  55
9  35  24  71  81

In [21]:
# los nuevos nombres se asignan a u nuevo df
df = df.rename(columns = {"A":"columna_1", "B":"columna_2", "C":"columna_3", "D":"columna_4"})
df

columna_1  columna_2  columna_3  columna_4
0         32          3         66         75
1         65         56         71         44
2         44         25         18         81
3         37         51         69         34
4         92         44         94         85
5         47         56         90         96
6         19         25         58          7
7         89         17         63         34
8         35         58          3         55
9         35         24         71         81

In [23]:
# inplace sirve para hacer el cambio sin asignarloa un nuevo df
df.rename(columns = {"A":"columna_1", "B":"columna_2", "C":"columna_3", "D":"columna_4"}, inplace=True)
df

columna_1  columna_2  columna_3  columna_4
0         32          3         66         75
1         65         56         71         44
2         44         25         18         81
3         37         51         69         34
4         92         44         94         85
5         47         56         90         96
6         19         25         58          7
7         89         17         63         34
8         35         58          3         55
9         35         24         71         81

In [24]:
df["columna_1"]

0    32
1    65
2    44
3    37
4    92
5    47
6    19
7    89
8    35
9    35
Name: columna_1, dtype: int32

In [33]:
df_subset = df[["columna_4","columna_3","columna_2"]]
df_subset

columna_4  columna_3  columna_2
0         75         66          3
1         44         71         56
2         81         18         25
3         34         69         51
4         85         94         44
5         96         90         56
6          7         58         25
7         34         63         17
8         55          3         58
9         81         71         24

In [34]:
df_subset.set_index(keys="columna_4", inplace=True)
df_subset

columna_3  columna_2
columna_4                      
75                66          3
44                71         56
81                18         25
34                69         51
85                94         44
96                90         56
7                 58         25
34                63         17
55                 3         58
81                71         24

In [35]:
df_subset.head(5)

columna_3  columna_2
columna_4                      
75                66          3
44                71         56
81                18         25
34                69         51
85                94         44

In [36]:
df_subset["columna_3"]

columna_4
75    66
44    71
81    18
34    69
85    94
96    90
7     58
34    63
55     3
81    71
Name: columna_3, dtype: int32

In [46]:
company = ["Apple", "Citigroup", "General_Electric", 
          "Pfizer", "Boing_Co", "AT&t", "Ford"]
price = [119.04, 43.19, 7.29, 37.95, 167.35, 27.33, 7.67]

df = pd.DataFrame(price, columns=["Stock_price"])
df

Stock_price
0       119.04
1        43.19
2         7.29
3        37.95
4       167.35
5        27.33
6         7.67

In [37]:
lista_de_listas = [np.random.random(10) for i in range(4)]
lista_de_listas

[array([0.26908048, 0.2116987 , 0.77484236, 0.69457172, 0.54626841,
        0.5345544 , 0.25817756, 0.55463614, 0.4628496 , 0.22794325]),
 array([0.52332399, 0.15193861, 0.04905273, 0.62322571, 0.67942465,
        0.35413168, 0.34161692, 0.01175337, 0.47400491, 0.26862209]),
 array([0.27776556, 0.99495547, 0.2609615 , 0.67665792, 0.32092977,
        0.87300173, 0.96440936, 0.8375854 , 0.39230258, 0.0241579 ]),
 array([0.51729089, 0.87857294, 0.33475445, 0.07811764, 0.6329945 ,
        0.50411893, 0.64136808, 0.70433798, 0.30813732, 0.11942684])]

In [42]:
nombre_de_columna = [f"columna{i}" for i in range(len(lista_de_listas[0]))]
print(nombre_de_columna)

['columna0', 'columna1', 'columna2', 'columna3', 'columna4', 'columna5', 'columna6', 'columna7', 'columna8', 'columna9']


In [50]:
df = pd.DataFrame(lista_de_listas, columns = nombre_de_columna)
df

columna0  columna1  columna2  columna3  columna4  columna5  columna6  \
0  0.269080  0.211699  0.774842  0.694572  0.546268  0.534554  0.258178   
1  0.523324  0.151939  0.049053  0.623226  0.679425  0.354132  0.341617   
2  0.277766  0.994955  0.260961  0.676658  0.320930  0.873002  0.964409   
3  0.517291  0.878573  0.334754  0.078118  0.632995  0.504119  0.641368   

   columna7  columna8  columna9  
0  0.554636  0.462850  0.227943  
1  0.011753  0.474005  0.268622  
2  0.837585  0.392303  0.024158  
3  0.704338  0.308137  0.119427

In [51]:
df = df.transpose()
df

0         1         2         3
columna0  0.269080  0.523324  0.277766  0.517291
columna1  0.211699  0.151939  0.994955  0.878573
columna2  0.774842  0.049053  0.260961  0.334754
columna3  0.694572  0.623226  0.676658  0.078118
columna4  0.546268  0.679425  0.320930  0.632995
columna5  0.534554  0.354132  0.873002  0.504119
columna6  0.258178  0.341617  0.964409  0.641368
columna7  0.554636  0.011753  0.837585  0.704338
columna8  0.462850  0.474005  0.392303  0.308137
columna9  0.227943  0.268622  0.024158  0.119427