In [1]:
import numpy as np

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Arreglo de 4 matrices, 3 arrelos por matriz, 2 atributos
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [5]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

In [6]:
# No inicializa los valores
np.empty([2,2])

array([[2.12199579e-314, 4.22786102e-307],
       [5.19757059e-321, 1.20317161e-311]])

In [7]:
np.array([1,2,3,4,'hola'])

array(['1', '2', '3', '4', 'hola'], dtype='<U11')

In [8]:
np.array([1,2,3,4,3.6])

array([1. , 2. , 3. , 4. , 3.6])

In [11]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5,5-1)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
a = np.array([[5,20,5,25],[1,20,25,20]])
a

array([[ 5, 20,  5, 25],
       [ 1, 20, 25, 20]])

In [17]:
b = np.append(a,[[1,3,2,1]], axis=0)
b

array([[ 5, 20,  5, 25],
       [ 1, 20, 25, 20],
       [ 1,  3,  2,  1]])

In [18]:
c = a.flatten()
c

array([ 5, 20,  5, 25,  1, 20, 25, 20])

In [19]:
print(a)
np.delete(a,3)
a

[[ 5 20  5 25]
 [ 1 20 25 20]]


array([[ 5, 20,  5, 25],
       [ 1, 20, 25, 20]])

In [20]:
print(b)
np.delete(b,[1],axis=0)
b

[[ 5 20  5 25]
 [ 1 20 25 20]
 [ 1  3  2  1]]


array([[ 5, 20,  5, 25],
       [ 1, 20, 25, 20],
       [ 1,  3,  2,  1]])

In [21]:
np.delete(b,[1],axis=0)

array([[ 5, 20,  5, 25],
       [ 1,  3,  2,  1]])

In [22]:
print(b)

[[ 5 20  5 25]
 [ 1 20 25 20]
 [ 1  3  2  1]]


In [23]:
print(a)

[[ 5 20  5 25]
 [ 1 20 25 20]]


In [24]:
b = a.copy()
b

array([[ 5, 20,  5, 25],
       [ 1, 20, 25, 20]])

In [25]:
b[0,0]=2
b

array([[ 2, 20,  5, 25],
       [ 1, 20, 25, 20]])

In [26]:
a.ndim

2

In [27]:
a.shape

(2, 4)

In [28]:
a.size

8

In [30]:
a = np.array([1,3,2,5,6,2,3,42,2,2,1,5])
a

array([ 1,  3,  2,  5,  6,  2,  3, 42,  2,  2,  1,  5])

In [31]:
a.shape

(12,)

In [32]:
b = a.reshape(3,4)
b

array([[ 1,  3,  2,  5],
       [ 6,  2,  3, 42],
       [ 2,  2,  1,  5]])

In [37]:
b[1,0:3]

array([6, 2, 3])

In [38]:
c = b.flatten()
c

array([ 1,  3,  2,  5,  6,  2,  3, 42,  2,  2,  1,  5])

In [41]:
a = np.arange(10,20,2)
b = np.arange(5,10,1)
print(a)
print(b)

[10 12 14 16 18]
[5 6 7 8 9]


In [42]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[15 18 21 24 27]
[ 50  72  98 128 162]
[5 6 7 8 9]
[2. 2. 2. 2. 2.]


In [7]:
a = np.arange(10,21,2).reshape(2,-1)
b = np.array([[2],[4],[2]])

In [43]:
print(a)
print(b)

[10 12 14 16 18]
[5 6 7 8 9]


In [44]:
np.dot(a,b)

510

In [45]:
print(a)

[10 12 14 16 18]


In [9]:
print(np.mean(a))
print(np.max(a))
print(np.median(a))
print(np.std(a))

15.0
20
15.0
3.415650255319866


In [10]:
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))

10
20
0
5


In [11]:
np.sqrt(a)

array([[3.16227766, 3.46410162, 3.74165739],
       [4.        , 4.24264069, 4.47213595]])

In [12]:
np.where(a<=12, 'Peque','Grande')

array([['Peque', 'Peque', 'Grande'],
       ['Grande', 'Grande', 'Grande']], dtype='<U6')

In [15]:
np.where((a<=18)&(a>=11),'mediano','extremo')

array([['extremo', 'mediano', 'mediano'],
       ['mediano', 'mediano', 'extremo']], dtype='<U7')

In [18]:
np.where(a<=12,'peque', np.where(a<=15,'mediano', 'Si es grande'))

array([['peque', 'peque', 'mediano'],
       ['Si es grande', 'Si es grande', 'Si es grande']], dtype='<U12')